---
title: "RIII project calculus extract concentration histogram"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output: github_document
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(janitor)
library(data.table)
library(tidyverse)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r}
extracts <- fread("00-documentation/calc_extract_ng_per_mg.tsv") %>%
  mutate(Type = "Calculus") %>%
  filter(Site != "Modern",
         Published != "No_info")

```

```{r}

# now bin the concentration like for GC content
breaks_extract = c(0.1,1,1.33,1.66,1.99,2.32,2.65,2.98,3.31,3.64,3.97,4,
                   5.2,6.4,7.6,8.8,10,11.2,12.4,13.6,14.8,16,
                   20.8,25.6,30.4,35.2,40,44.8,49.6,54.4,59.2,64,
                   83.2,102,121,140,160,179,198,217,236,256,
                   281,306,332,357,383,408,433,459,484,510)

extracts_binned <- extracts %>%
  mutate(conc = cut(calc, breaks = breaks_extract, include.lowest = TRUE)) %>%
  group_by(Type, conc) %>%
  summarise(counts = n()) %>%
  complete(conc) %>%
  ungroup() %>%
  mutate(counts = ifelse(is.na(counts), 0, counts))

extracts %>%
  summarize(median_conc = median(calc))

```



```{r}

conc_plot <- extracts_binned %>%
   mutate(conc = factor(conc, level=c("[0.1,1]","(1,1.33]","(1.33,1.66]","(1.66,1.99]","(1.99,2.32]","(2.32,2.65]","(2.65,2.98]","(2.98,3.31]","(3.31,3.64]","(3.64,3.97]","(3.97,4]","(4,5.2]","(5.2,6.4]","(6.4,7.6]","(7.6,8.8]","(8.8,10]","(10,11.2]","(11.2,12.4]","(12.4,13.6]","(13.6,14.8]","(14.8,16]","(16,20.8]","(20.8,25.6]","(25.6,30.4]","(30.4,35.2]","(35.2,40]","(40,44.8]","(44.8,49.6]","(49.6,54.4]","(54.4,59.2]","(59.2,64]","(64,83.2]","(83.2,102]","(102,121]","(121,140]","(140,160]","(160,179]","(179,198]","(198,217]","(217,236]","(236,256]","(256,281]","(281,306]","(306,332]","(332,357]","(357,383]","(383,408]","(408,433]","(433,459]","(459,484]","(484,510]"))) %>%
  ggplot(., aes(x = counts, y = conc)) +
         geom_bar(aes(fill = Type), stat = "identity") +
         theme_minimal(base_size = 12) +
         theme(axis.text.x = element_text(angle = 0, hjust = 1, vjust = 0.5, size = 14)) +
         theme(axis.text.y = element_text(size = 12)) +
         scale_fill_manual(values = c("#05A8AA")) +
         scale_x_continuous(breaks=scales::pretty_breaks(n=10)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=10)) +
         theme(legend.position="none") +
         ylab("[DNA] (ng/mg)") +
         xlab("No. samples")
conc_plot

# ggsave("./06-publication/prelim_figs/extract_concentration_plot.pdf", plot = conc_plot, device = "pdf",
#        scale = 1, width = 5, height = 10, units = c("in"), dpi = 300)

```


















