---
title: "RIII calculus Figure 2"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---


```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(tidyverse)
library(gplots)
library(viridis)
library(cowplot)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../../.."))
```

# 

```{r load_metadata}
riii_metadata <- fread("./00-documentation/riii_metadata.tsv")

```

```{r}
# load sourcetracker table
riii_results <- fread("./05-results/sourcetracker_sink_predictions_by_library.tsv") %>%
  select(SampleID, modernCalculus, subPlaque, supPlaque, urbanGut, ruralGut, skin, sediment, archBone, Unknown)

```


```{r set_colors}
reduced_colors <- c(modernCalculus = "#80b1d3", plaque = "#b3de69", stool = "#fb8072", skin = "#ffffb3",sediment = "#bebada", archBone = "#fdb462", Unknown = "#d9d9d9")
```


Plot bar charts

```{r}

st_reduced_plot_riii <- riii_results %>%
  filter(str_detect(SampleID, "R3|G12|B61|SMH")) %>%
  mutate(plaque = subPlaque + supPlaque,
         stool = urbanGut + ruralGut) %>%
  select(-matches("subPlaque|supPlaque|Gut")) %>%
  pivot_longer(!SampleID, names_to = "Sources", values_to = "Percent") %>%
  # gather("Sources", "Percent",2:ncol(.)) %>%
  mutate(Percent = Percent * 100) %>%
  mutate(Sources = fct_relevel(Sources, "Unknown","archBone","sediment","skin","stool","plaque","modernCalculus")) %>%
  mutate(SampleID = fct_relevel(SampleID, "R31","R32A","R32B","R33",
                                "SMH005.A0101","SMH005.A0102","SMH007.A0101","SMH007.A0102","SMH008.A0101","SMH008.A0102",
                                "G12_25_2E5_YaleRun1","G12_25_2E6_YaleRun1","G12_25_2E7_YaleRun1","G12_25_2E8_YaleRun1",
                                "G12_2E5_YaleRun2","G12_2E6_YaleRun2","G12_2E7_YaleRun2","G12_2E8_YaleRun2",
                                "G12_pub","B61")) %>%
  # filter(!str_detect(SampleID, "CMB")) %>%
  ggplot(., aes(x = SampleID, y = Percent, fill = Sources)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 8) +
         scale_fill_manual(values = reduced_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
               axis.text = element_text(size = 8)) +
         geom_hline(yintercept=90, linetype="dotted", color = "gray50") +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         ylab("% attributed to source")
st_reduced_plot_riii

# ggsave("./06-publication/main_figures/Figure_2/riii_st_reduced_plot.pdf", plot = st_reduced_plot_riii, device = "pdf",
#        scale = 1, width = 6, height = 3, units = c("in"), dpi = 300)


```











